### PR TITLE
Upgraded Umbraco OpenID Connect example package to Umbraco 12.2.0.

### PR DESCRIPTION
**Pull request by jbreuer**
I'm the developer of the [Umbraco OpenID Connect example package](https://github.com/jbreuer/Umbraco-OpenIdConnect-Example#umbraco-openid-connect-example-package). I always upgrade to the newest version of Umbraco because in the past some versions broke the OpenID Connect implementation.

### CODE REVIEW

**Comment by jbreuer** [comment]
I did something similar last year which also got merged: https://github.com/umbraco/HacktoberfestActivityLog/pull/16

**Comment by mikecp** [comment]
Hi @jbreuer ,

Thanks a lot for your contribution and for maintaining your package to make sure it runs on the latest version 👍

**Comment by mikecp** [comment]
Hi @jbreuer,

Thanks for the clarification and H5YR for making those extra checks 👍

**Comment by nul800sebastiaan** [comment]
Thanks Jeroen, unfortunately this is not a contribution that counts for hacktoberfest, I understand it's work for you but accepting contributions that merely test that something that should work still works is not on our list of acceptable contributions for hacktoberfest. I'll make this more clear in next year's rules because I can see it could be ambiguous at the moment.

**Comment by nul800sebastiaan** [comment]
Ps. I'm aware a similar one was accepted last year but we've become a bit more strict to avoid encouraging things that are outside of the rules. Sorry to disappoint this time around!

**Comment by jbreuer** [comment]
Hi @nul800sebastiaan,,

I understand that work like this won't be accepted next year, but for this year it feels a bit unfair. I tried my best this year with 3 PRs:

https://github.com/umbraco/HacktoberfestActivityLog/pull/63 - Added blog post 

https://github.com/umbraco/HacktoberfestActivityLog/pull/67 - Upgraded Umbraco OpenID Connect example package to Umbraco 12.2.0.

https://github.com/umbraco/HacktoberfestActivityLog/pull/77 - Upgraded Umbraco OpenID Connect example package to Umbraco 12.3.0-rc. 

One PR even got merged and was accepted by @mikecp. Reverting it 1 day before Hacktoberfest ends means I don't have time to create another PR. I'll make different contributions next year, but for this year I thought this was also valid.

**Pull request merged**
