### PR TITLE
Added no-code contribution

### PR DESCRIPTION
**Pull request by royberris**

### CODE REVIEW

**Comment by emmagarland** [comment]
Hi @royberris 

Thanks for your contribution about the Hackathon event, that sounds great!

I've made a few tweaks and resolved the merge conflicts. 

Two questions:

1. Are you happy for me to change your name to a Github link to your profile?
2. We have the link to the company, but I was wondering if you can add a link to the event at all (similarly to Karl Tynan's contribution)? Or add a couple more details about how you did it.

Many thanks!

Emma

**Comment by nul800sebastiaan** [comment]
And make sure to add you were the (co?)organizer!

**Comment by royberris** [comment]
Hi, I was a bit under the weather and forgot to respond. I'll update it

**Comment by royberris** [comment]
Hi @emmagarland 

I don't have a link because it was an internal event. So no public links or posts or anything. I do have a picture :D 

image

**Comment by mikecp** [comment]
Thanks @royberris for the update and picture, I think it's all good to merge now 😁

And most importantly: thanks for organizing this internal hackathon 👍🎉

**Pull request merged**
