### PR TITLE
Added DDDEastMidlands talk

### PR DESCRIPTION
**Pull request by poornimanayar**

### CODE REVIEW

**Comment by emmagarland** [comment]
Hi @poornimanayar, thanks for your PR to add your contribution to Hacktoberfest 2023 for Umbraco!

Just one change to make and it can be merged

**Comment by poornimanayar** [comment]
I think I have updated it :-) (from my phone)

**Review by emmagarland — COMMENTED** [review]
Updated in edit mode 👍

**Comment by emmagarland** [comment]
Hi @poornimanayar, I've done a little tweak and this has now been merged 👍

Thanks for your contribution of the talk!

**Pull request merged**
