### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Anugya43**
Wrote an article inspired by a previous year article

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
This is not an Umbraco related article, so is not eligible.

**Comment by Anugya43** [comment]
This was my first hacktoberfest, and thanks to you putting both my merges under spam, I am now banned from further participation. Yes, I do not know much about the topic, but I tried knowing a bit while writing about it, as I did for all my contributions, 3 of my 4 PRs were merged, and this was my 4th one, but now my fest is ruined.

**Comment by nul800sebastiaan** [comment]
I think you really didn't read the rules very well. Also, none of your 5 other PRs have been accepted yet, these 2 have been rejected because they are wildly outside of the rules.

**Comment by nul800sebastiaan** [comment]
FYI you can check your activity here: https://github.com/search?q=author%3AAnugya43+created%3A%3E%3D2024-09-30&type=pullrequests&s=created&o=desc 

The rest of the PRs are just open as you can see, with no response:

image


Make sure to review the rules again here: https://hacktoberfest.com/participation#pr-mr-details

**Pull request closed without merging**
