### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Truealex4**

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Hi @Truealex4 can you tell us a little more about this please?

**Comment by Truealex4** [comment]
https://github.com/umbraco/Umbraco-CMS/issues/13250
https://github.com/umbraco/Umbraco-CMS/issues/13251

Both of the above were created as a result of my investigation. apologies, am new to GitHub @nul800sebastiaan but wanted to be able to add my contributions.

**Review by mikecp — APPROVED** [review]

**Comment by mikecp** [comment]
Thanks @Truealex4 for the accessibility reviews 👍

**Comment by Truealex4** [comment]
Hi Sebastian,

Thanks for getting in touch – the sizing chart is for a woman – is it a universal fit as I am a man?

If so then am happy to go LARGE

Regards
Alex

**Comment by nul800sebastiaan** [comment]
> the sizing chart is for a woman

@Truealex4 if you look closer, there's two charts attached 😅

**Comment by Truealex4** [comment]
Whoopsie – let’s stick with Large

Good job I do not work in QA!!!!!!

**Pull request merged**
